version: "3.8"

services:
  build-x64:
    build:
      context: ..
      dockerfile: docker/Dockerfile.linux
    container_name: dodhooks-build-x64
    environment:
      - BUILD_ARCH=x86_64
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: ["/docker-build.sh"]

  build-x86:
    build:
      context: ..
      dockerfile: docker/Dockerfile.linux
    container_name: dodhooks-build-x86
    environment:
      - BUILD_ARCH=x86
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: ["/docker-build.sh"]
